### ISSUE TITLE
[QUESTION]:How to collect trace data from skywalking and flush the data to the default collector?

### ISSUE THREAD

**Issue by tuhao1020** [alibaba/ilogtail#52]
I use the following config file， if I add the flusher_grpc,  ilogtail will panic
```
{
  "inputs": [
    {
      "detail": {
        "Address": "localhost:11801"
      },
      "type": "service_skywalking_agent_v3"
    }
  ],
  "processors": [
    {
      "type": "processor_default"
    }
  ],
  "flushers": [
    {
      "type": "flusher_stdout",
      "detail": {
        "FileName": "quickstart_1.stdout"
      }
    },
    {
      "type": "flusher_grpc",
      "detail": {
        "Address": "localhost:11800"
      }
    }
  ]
}
```

```
load config ./global.json bin/sw.json ./default_flusher.json
load log config /private/var/folders/lt/gstgm3fd0jj5hlcz0ryw6fxm0000gn/T/GoLand/plugin_logger.xml 
panic: protobuf tag not enough fields in JVMMetricCollection.state: 

goroutine 57 [running]:
github.com/gogo/protobuf/proto.(*unmarshalInfo).computeUnmarshalInfo(0xc0004b8be0)
        /Users/tuhao/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/table_unmarshal.go:341 +0x219e
github.com/gogo/protobuf/proto.(*unmarshalInfo).unmarshal(0xc0004b8be0, {0xc000c90240}, {0xc00070a480, 0x226, 0x226})
        /Users/tuhao/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/table_unmarshal.go:138 +0x8c
github.com/gogo/protobuf/proto.(*InternalMessageInfo).Unmarshal(0xc000092240, {0xe7af328, 0xc000c90240}, {0xc00070a480, 0x226, 0x226})
        /Users/tuhao/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/table_unmarshal.go:63 +0x165
github.com/gogo/protobuf/proto.(*Buffer).Unmarshal(0xc0000392f0, {0xe7af328, 0xc000c90240})
        /Users/tuhao/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/decode.go:424 +0x3a5
github.com/gogo/protobuf/proto.Unmarshal({0xc00070a480, 0x226, 0x226}, {0xe7af328, 0xc000c90240})
        /Users/tuhao/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/decode.go:342 +0x213
github.com/alibaba/ilogtail/pkg/protocol.Codec.Unmarshal({}, {0xc00070a480, 0x226, 0x226}, {0x64e96e0, 0xc000c90240})
        /Users/tuhao/dev/golang/ilogtail/pkg/protocol/sls_logs.pb.helper.go:38 +0xdb
google.golang.org/grpc.(*Server).processUnaryRPC.func2({0x64e96e0, 0xc000c90240})
        /Users/tuhao/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1274 +0x128
github.com/alibaba/ilogtail/plugins/input/skywalkingv3/skywalking/network/language/agent/v3._JVMMetricReportService_Collect_Handler({0x639fca0, 0xc00041e930}, {0x691f940, 0xc0000392c0}, 0xc000c901e0, 0x0)
        /Users/tuhao/dev/golang/ilogtail/plugins/input/skywalkingv3/skywalking/network/language/agent/v3/JVMMetric_grpc.pb.go:70 +0x95
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004a76c0, {0x6955140, 0xc0001c2480}, 0xc000138ea0, 0xc00030a2d0, 0x7d10ee0, 0x0)
        /Users/tuhao/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297 +0x14c9
google.golang.org/grpc.(*Server).handleStream(0xc0004a76c0, {0x6955140, 0xc0001c2480}, 0xc000138ea0, 0x0)
        /Users/tuhao/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626 +0x85e
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /Users/tuhao/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941 +0x11d
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/tuhao/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:939 +0x345
Exiting.
```

**Comment by EvanLjp** [comment]
the flusher protocol of gRPC is not the same as the skywalking grpc protocol. 
more protocol details please see [here](https://github.com/alibaba/ilogtail/tree/main/pkg/protocol)

**Comment by tuhao1020** [comment]
Thanks!
If I want to flush the trace data to the dafault collector, I should create a custom flusher plugin, right?

**Comment by qiansheng91** [comment]
Yes, That's right. You should create a new flusher if you want to that
